version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - worktree
  ignore:
  - dependency-name: "@babel/*"
    versions:
    - ">= 0"
  - dependency-name: core-js
    versions:
    - ">= 0"
  - dependency-name: next
    versions:
    - 9.x
  - dependency-name: prettier
    versions:
    - ">= 0"
  - dependency-name: raw-loader
    versions:
    - ">= 0"
  - dependency-name: react-dom
    versions:
    - ">= 0"
  - dependency-name: react-is
    versions:
    - ">= 0"
  - dependency-name: react-test-renderer
    versions:
    - ">= 0"
  - dependency-name: size-limit
    versions:
    - ">= 0"
  - dependency-name: tslint
    versions:
    - 5.x
  - dependency-name: typescript
    versions:
    - ">= 0"
  - dependency-name: downshift
    versions:
    - 6.1.0
  - dependency-name: nodemod
    versions:
    - 2.7.2
  - dependency-name: webpack-cli
    versions:
    - 4.2.0
  - dependency-name: danger
    versions:
    - 10.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: react-inspector
    versions:
    - 5.0.1
